### ISSUE TITLE
Is it worth renaming private variables?

### ISSUE THREAD

**Issue by Ts-Pytham** [linkdotnet/StringBuilder#20]
Hi! I like your project! But, I have a question,  is it worth renaming private variables?
I ask this because in the C# convention they recommend using underscore to private variables.

**Comment by linkdotnet** [comment]
Hey. Nice to have you on board :D

It is quite funny because depending on the team, Microsoft is contradicting itself from time to time. [Here](https://social.technet.microsoft.com/wiki/contents/articles/38011.c-language-best-practices.aspx) is an article where they state, don't underscore.

At the end of the day, I am very indifferent about that as it doesn't hinder nor boost me. I stuck to that some time ago and it was fine :D. If someone has strong feelings I have absolutely no problem changing that.

There is also almost risk as the `ValueStringBuilder` is a `ref struct` making serialization almost impossible. Almost because you could work with underlying memory slices and ordering of properties and fields (no one should do that anyway).
